### ISSUE TITLE
Apparent issues processing Japanese characters

### ISSUE THREAD

**Issue by SFTSM1L3** [kaegi/alass#15]
error: parsing subtitle file '51.srt' failed
caused by: parsing the subtitle data failed
caused by: parse error at line `0`
〈今度の勝負も 俺が勝つ！〉'7ばよ！〉てんならなね｡
caused by: invalid digit found in string

not: run with environment variable 'RUST_BACKTRACE=1' for detailed stack traces

**Comment by kaegi** [comment]
Is this the first line (as indicated by `line 0`) in the file? If so, then this is not a valid SRT file...

Otherwise it would be helpful to provide the whole file.

**Comment by SFTSM1L3** [comment]
I found a new SRT file, but there is a bit of a problem with the program. Is it supposed to be able to match the srt with the .mp4 episode? It won't even load the video
D:\Downloads\Season 1 [1 - 57]>alass-cli 1.mp4 1.srt New1.srt
error: processing video file '1.mp4' failed
caused by: failed to extract voice segments from file '1.mp4'
caused by: failed to extract metadata from '1.mp4' using command 'ffprobe -v error -show_entries format=duration:stream=index,codec_long_name,channels,duration,codec_type -of json 1.mp4'
caused by: failed to spawn subprocess 'ffprobe -v error -show_entries format=duration:stream=index,codec_long_name,channels,duration,codec_type -of json 1.mp4'
caused by: The system cannot find the file specified. (os error 2)

not: run with environment variable 'RUST_BACKTRACE=1' for detailed stack traces
[Here are the files I attempted to use ](https://mega.nz/file/NpAQmA5D#qb_nnuwCS-PTSVPCjPNokKgYiXKpCH3o2YOa48vSp7A)

**Comment by kaegi** [comment]
Yes, alass is supposed to be able to do that. It seems like ffprobe/ffmpeg can not be found.

Did you compile it from source (if so, you must have ffprobe and ffmpeg in your PATH or provide the path with ALASS_FFPROBE and ALASS_FFMPEG) or did you download the ZIP file from the releases section? (then it should work if you use `alass.bat` if you do not change the folder structure)

**Comment by SFTSM1L3** [comment]
I compiled from cargo, I do not know what went wrong though.

**Comment by SFTSM1L3** [comment]
I downloaded the app and it works perfect, Thanks. Your work will benefit a lot of people who want to learn a new language.
