### ISSUE TITLE
Looking forward to a basic Windows GUI

### ISSUE THREAD

**Issue by wellloaded** [kaegi/alass#20]
As per title it would be great to have a very simple interface where video and subtitles can be dropped for processing.

Perhaps a queue management could also be added?

Thanks!

**Comment by kaegi** [comment]
A GUI would certainly be nice :) But I'm not using Windows and will only use this project as a command-line app myself (and using bash scripts process whole series at once). A special GUI would also be beyond the scope of this repository. The alignment algorithm can be easily use as a library and therefore be included inside any 3rd party application (https://github.com/Wsiegenthaler/alass-ffi also did some re-packaging target at developers).

I'm hoping for interested people to implement this in their preferred tools/GUIs/websites! For example https://github.com/joaquintorres/autosubsync-mpv is an auto-align plugin for the MPV video player that uses alass. It's always nice to see :)
