### ISSUE TITLE
batch script for Alass

### ISSUE THREAD

**Issue by BramFr** [kaegi/alass#21]
Alass works great :) so here a batch script. This will override the existing sub with the new one.

https://github.com/BramFr/alass-batch

**Comment by kaegi** [comment]
Cool!

**Comment by wellloaded** [comment]
You must not assume that a subtitles processed with alass produce an usable output 100% of the times. Based on my usage of the last 3 months and few hundreds subtitles processed I'd say we're in the range of 85-90% success rate.

TL;DR don't overwrite by default, create a copy.

**Comment by kaegi** [comment]
I'm closing this issue as there is nothing to change for this repository :)
