### ISSUE TITLE
Auto detect encoding

### ISSUE THREAD

**Issue by mehdipourfar** [kaegi/alass#22]
Hi. Thanks for your great project. I want to know if this package will be maintained anymore? I wanna add uchardet package as dependency so that there will be no need to set --encoding-inc and --encoding-ref.

**Comment by kaegi** [comment]
It is now implemented in https://github.com/kaegi/alass/commit/874f02d9577182752a0f969b6d6b98fd65bdf1fc . I used the Rust variant https://github.com/thuleqaid/rust-chardet to keep the build process simple.
