### ISSUE TITLE
Feature request: allow different subtitles charsets (other than UTF8) to be processed

### ISSUE THREAD

**Issue by wellloaded** [kaegi/alass#25]
I'm having some issues and have to use iconv to force a UTF-8 conversion of my .rtf files as alass would not process them otherwise.

Can different charsets be considered at alass code level?

Thanks

**Comment by kaegi** [comment]
Have you tried `--encoding-inc` and `--encoding-ref`?

**Comment by wellloaded** [comment]
> 
> 
> Have you tried `--encoding-inc` and `--encoding-ref`?

Actually I didn't but it seems like the user is expected to know the charset of the incorrect subtitles file (or the reference one)

It is nice to see this was "considered" still it needs manual interaction which is what I was trying to avoid.
I'm wondering if the charset can be worked out automatically by alass directly (e.g. like the **file** command does)

Thanks!

**Comment by wellloaded** [comment]
As a matter of facts I have found that file -bi is NOT reliable enough. So anybody facing this problem I would strongly suggest forcing a UTF-8 of the source .srt like this (you'll need vim installed):

**vim +'set nobomb | set fenc=utf8 | x' <filename>**

So the above script is further developed into:

```
Video=$(ls -1 | grep -Ei '*.avi$|*.mkv$|.*asf$|*.wmv$|*.mp4$|*.mpg$|*.mpeg$|*.divx$|*.m4v$' 2>/dev/null)
SubName=$(ls -1 | grep -Ei '*.srt$' 2>/dev/null | head -1)
vim +'set nobomb | set fenc=utf8 | x' $SubName
CharSet=$(file -bi ./"$SubName" | cut -f2 -d "=")
SubNameResync=".alass"_$SubName
alass --encoding-inc "$CharSet" "$Video" "$SubName" "$SubNameResync"
```

HTH

**Comment by kaegi** [comment]
Auto-detection of character encoding using https://github.com/thuleqaid/rust-chardet implemented in https://github.com/kaegi/alass/commit/874f02d9577182752a0f969b6d6b98fd65bdf1fc.
