### ISSUE TITLE
Error while decoding subtitle

### ISSUE THREAD

**Issue by Ruke805** [kaegi/alass#31]
First, good job for this tool

I've tried with a subtitle and I got this error:

```
error: parsing subtitle file 'F:\Ani\subtitle.srt' failed
caused by: error while decoding subtitle from bytes to string (wrong charset encoding?)

not: run with environment variable 'RUST_BACKTRACE=1' for detailed stack traces
```

What's going wrong?

**Comment by kaegi** [comment]
Usually text files (and special characters in it) are encoded as UTF-8, but sometimes files have other encodings which cannot be decoded using the default UTF-8 decoder. The lastest commit https://github.com/kaegi/alass/commit/874f02d9577182752a0f969b6d6b98fd65bdf1fc in this project actually implements auto-detection of the character encoding.

The most commonly used incompatible encoding is `iso-8859-1`. You can specify the file encoding for the "incorrect file" with `--encoding-inc=iso-8859-1` or for the "reference file" with `--encoding-ref=iso-8859-1`.

**Comment by kaegi** [comment]
On linux/unix machines the tool `chardetect` can guess the encoding of the file (this is what the latest commit does automatically).

Related to https://github.com/kaegi/alass/issues/25.

**Comment by Ruke805** [comment]
Nice, It worked well adding this flag
