### ISSUE TITLE
Support embedded subtitles?

### ISSUE THREAD

**Issue by WyseNynja** [kaegi/alass#8]
In addition to external SRT files, I have a bunch of MKV files that have subtitles embedded in them. Is it possible for `alass` to correct those in-place?

If not, do you have any recommendations for automatically extracting and then correcting them?

**Comment by kaegi** [comment]
I usually extract subtitles with `ffmpeg` like [this](https://superuser.com/a/927507).

These are strange movie files... Why would somebody embed a wrong subtitle into a movie? I would assume that this is a very rare case and does not warrant the extra complexity inside alass (which would be exactly calling the given `ffmpeg` command but requires extra arguments in alass specifying the subtitle stream).

**Comment by kaegi** [comment]
One related thing that is on my TODO list is _aligning to_ subtitles embedded in `.mkv` instead of performing a voice-activity-detection on the audio. This is probably not what you meant though.
